main: me.ase34.citylanterns.CityLanterns
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ase34
commands:
  citylanternsselect:
    aliases: cls
    permission: citylanterns.select
    description: Command for selecting lanterns
    usage: |
        /<command> [<group> [we]]
        <group>
        §f  The group the lanterns will
        §f  be added. Default is 'main'.
        we
        §f  Set all lanterns to <group>
        §f  in the WorldEdit selection.
permissions:
  citylanterns.sl:
    default: op
    description: Allows to use the /sl command.
  citylanterns.gls:
    default: op
    description: Allows to use the /gls command.
  citylanterns.sls:
    default: op
    description: Allows to use the /sls command.    
  citylanterns.*:
    default: false
    description: Allows to use all CityLanterns commands.
  