main: me.ase34.citylanterns.CityLanterns
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ase34
softdepend: [WorldEdit] 
commands:
  citylanternsselect:
    aliases: cls
    permission: citylanterns.select
    description: Command for selecting lanterns
    usage: |
        /<command> [<group> [we]]
        <group> - The group the lanterns will be added. Default is 'main'.
        §f 
        we - Set all lanterns to <group> in the WorldEdit selection.
  citylanternsgroups:
    aliases: clg
    permission: citylanterns.groups
    description: Command for getting group settings
    usage: |
        /<command> [<group>]
        <group> - If specified, prints deitailed information about that group. If not, a list of groups will be displayed.
  citylanternssettings:
    aliases: clsettings
    permission: citylanters.settings
    description: Command for setting group settings and settings in general
    usage: |
        /<command> [<group>] day|night|thunder <value>
        <group> - The group the lanterns will be added. Default is 'main'.
        §f 
        <value> - If 'day' or 'night' then a number is expected, if 'thunder' then either 'true' or 'false' is expected. 
permissions:
  citylanterns.select:
    default: op
  citylanterns.groups:
    default: op
  