main: me.ase34.citylanterns.CityLanterns
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ase34
softdepend: [WorldEdit] 
commands:
  citylanternsselect:
    aliases: cls
    permission: citylanterns.select
    description: Command for selecting lanterns
    usage: |
        /<command> [<group> [we]]
        <group>
        §f  The group the lanterns will
        §f  be added. Default is 'main'.
        we
        §f  Set all lanterns to <group>
        §f  in the WorldEdit selection.
  citylanternsgroups:
    aliases: clg
    permission: citylanterns.groups
    description: Command for getting group settings
    usage: |
        /<command> [<group>]
        <group>
        §f  If specified, prints deitailed
        §f  information about that group.
        §f  If not, a list of groups will
        §f  be displayed.
permissions:
  citylanterns.select:
    default: op
  citylanterns.groups:
    default: op
  